'use strict';
const mongoose = require( 'mongoose' );
const Schema = mongoose.Schema;
const ObjectId = Schema.Types.ObjectId;
const Mixed = Schema.Types.Mixed;

var pieceSchema = Schema( {
    objectID: Number,
    isHighlight: Boolean,
    accessionNumber: String,
    accessionYear: String,
    isPublicDomain: Boolean,
    primaryImage: String,
    primaryImageSmall: String,
    additionalImages: Mixed,
    constituents: Mixed,
    department: String,
    objectName: String,
    title: String,
    culture: String,
    period: String,
    dynasty: String,
    reign: String,
    portfolio: String,
    artistRole: String,
    artistPrefix: String,
    artistDisplayName: String,
    artistDisplayBio: String,
    artistSuffix: String,
    artistAlphaSort: String,
    artistNationality: String,
    artistBeginDate: String,
    artistEndDate: String,
    artistGender: String,
    artistWikidata_URL: String,
    artistULAN_URL: String,
    objectDate: String,
    objectBeginDate: Number,
    objectEndDate: Number,
    medium: String,
    dimensions: String,
    dimensionsParsed: Number,
    measurements: Mixed,
    creditLine: String,
    geographyType: String,
    city: String,
    state: String,
    county: String,
    country: String,
    region: String,
    subregion: String,
    locale: String,
    locus: String,
    excavation: String,
    river: String,
    classification: String,
    rightsAndReproduction: String,
    linkResource: String,
    metadataDate: Mixed,
    repository: String,
    objectURL: String,
    tags: Mixed,
    objectWikidata_URL: String,
    isTimelineWork: Boolean,
    GalleryNumber: String,
} );

module.exports = mongoose.model( 'Piece', pieceSchema );
